# Generated by Django 5.2 on 2025-04-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0002_pricingpackage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingpackage',
            name='description',
        ),
        migrations.AlterField(
            model_name='pricingpackage',
            name='features',
            field=models.CharField(max_length=500),
        ),
    ]
