# Generated by Django 5.2 on 2025-04-17 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0003_remove_pricingpackage_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='pricing_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='photobooth.pricingpackage'),
        ),
    ]
