# Generated by Django 5.2 on 2025-05-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photobooth', '0004_request_pricing_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
    ]
